# Generated by Django 2.2.7 on 2019-11-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('family', models.TextField()),
                ('category', models.TextField(choices=[('d', 'display'), ('h', 'handwriting'), ('m', 'monospaced')])),
                ('is_body', models.BooleanField(default=True)),
                ('is_serif', models.BooleanField(default=True)),
                ('is_italic', models.BooleanField(default=False)),
                ('weight', models.PositiveIntegerField(choices=[('100', 'Thin'), ('200', 'Extra Light'), ('300', 'Light'), ('400', 'Regular'), ('500', 'Medium'), ('600', 'Semi Bold'), ('700', 'Bold'), ('800', 'Extra Bold'), ('900', 'Black')])),
                ('url', models.URLField()),
            ],
        ),
    ]
