# Generated by Django 2.2.7 on 2019-11-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='weight',
            field=models.PositiveIntegerField(choices=[('100', 'Thin'), ('200', 'Extra Light'), ('300', 'Light'), ('400', 'Regular'), ('500', 'Medium'), ('600', 'SemiBold'), ('700', 'Bold'), ('800', 'Extra Bold'), ('900', 'Black')]),
        ),
    ]
