# Generated by Django 2.2.7 on 2019-11-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0003_auto_20191118_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='font',
            name='weight',
            field=models.TextField(),
        ),
    ]
