# Generated by Django 2.2.7 on 2019-11-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0004_auto_20191118_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='font',
            name='family',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='font',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='font',
            name='weight',
            field=models.CharField(max_length=255),
        ),
    ]
