# Generated by Django 2.2.7 on 2019-11-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0006_auto_20191118_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='weight',
            field=models.CharField(choices=[('thin', 'Thin'), ('extralight', 'Extra Light'), ('light', 'Light'), ('regular', 'Regular'), ('medium', 'Medium'), ('semibold', 'Semi Bold'), ('bold', 'Bold'), ('extrabold', 'Extra Bold'), ('black', 'Black')], max_length=20),
        ),
    ]
