# Generated by Django 2.2.7 on 2019-11-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0007_auto_20191118_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font1', to='fonts.Font')),
                ('font2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font2', to='fonts.Font')),
            ],
        ),
    ]
