# Generated by Django 2.2.7 on 2019-12-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('name', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('is_body', models.BooleanField(default=True)),
                ('is_serif', models.BooleanField(default=True)),
                ('is_italic', models.BooleanField(default=False)),
                ('weight_num', models.IntegerField(default=400)),
                ('weight_str', models.CharField(default='regular', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.Family')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
