# Generated by Django 2.2.7 on 2019-12-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='string',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
