# Generated by Django 2.2.7 on 2019-12-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0002_auto_20191202_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['weight']},
        ),
    ]
