# Generated by Django 2.2.7 on 2019-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
