# Generated by Django 2.2.7 on 2019-11-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0002_fontcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FontCategory',
        ),
    ]
