# Generated by Django 2.2.7 on 2019-11-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0003_auto_20191119_0431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
