# Generated by Django 2.2.7 on 2019-11-19 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0004_auto_20191119_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fontpair',
            options={'verbose_name_plural': 'Pairings'},
        ),
    ]
