# Generated by Django 2.2.7 on 2019-11-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0005_auto_20191119_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
    ]
