# Generated by Django 2.2.7 on 2019-11-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0006_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('string', models.CharField(max_length=255)),
            ],
        ),
    ]
